name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup Java 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: chmod build script
      run: chmod +x gradlew

    - name: Verify Plugin
      run: ./gradlew verifyPlugin
      env:
        IS_CI: "True"

    - name: Build
      run: ./gradlew buildPlugin
      env:
        IS_CI: "True"

    - name: Upload Artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        # TODO: This uploads a zip called `distributions`; see what we can do to just upload the produced plugin itself.
        name: distributions
        path: build/distributions
