name: IntelliJ Platform Plugin Compatibility

on:
  push:
  pull_request:
  schedule:
    - cron:  '30 5 1/4 * *'

jobs:
  compatibility:
    name: Ensure IntelliJ plugin compatibility.
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: chmod build script
        run: chmod +x gradlew

      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin

      - name: Verify Plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
        with:
          ide-versions: |
            ideaIC:2021.3.2
            ideaIU:2021.3.2
            pycharmPC:2021.3.2
            pycharmPY:2021.3.2
            goland:2021.3.2
            clion:2021.3.2

      - name: Get log file path and print contents
        run: |
          echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}
